/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 9e4c2c3c340761e6d7ea56416590f6da)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "ChatAgent";
	}
	interface Env {
		AI: Ai;
		ANTHROPIC_API_KEY: string;
		ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
		INGESTION_WORKFLOW: Workflow /* IngestionPipeline */;
		MODEL: string;
	}
}
interface Env extends Cloudflare.Env { }
